spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qwe..A
    url: jdbc:mysql://localhost:3306/visual?charset=utf8&autocommit=true&autoReconnect=true&serverTimezone=GMT%2B8

